[package]
name = "mugraph-node"
version = "0.1.0"
edition = "2021"

[dependencies]
mugraph-core = { workspace = true }
axum = { workspace = true }
redb = { workspace = true }
tempfile = { workspace = true }
color-eyre = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
rand_chacha = { workspace = true }
serde_json = { workspace = true }
onlyerror = { workspace = true }
tracing = { workspace = true }
metrics = { workspace = true }
